.PHONY: clean All

All:
	@echo "----------Building project:[ InitializingVariable - Debug ]----------"
	@cd "InitializingVariable" && "$(MAKE)" -f  "InitializingVariable.mk"
clean:
	@echo "----------Cleaning project:[ InitializingVariable - Debug ]----------"
	@cd "InitializingVariable" && "$(MAKE)" -f  "InitializingVariable.mk" clean
