.PHONY: clean All

All:
	@echo "----------Building project:[ InitializingVariables - Debug ]----------"
	@cd "main" && "$(MAKE)" -f  "InitializingVariables.mk"
clean:
	@echo "----------Cleaning project:[ InitializingVariables - Debug ]----------"
	@cd "main" && "$(MAKE)" -f  "InitializingVariables.mk" clean
