.PHONY: clean All

All:
	@echo "----------Building project:[ IfStatement - Debug ]----------"
	@cd "IfStatement" && "$(MAKE)" -f  "IfStatement.mk"
clean:
	@echo "----------Cleaning project:[ IfStatement - Debug ]----------"
	@cd "IfStatement" && "$(MAKE)" -f  "IfStatement.mk" clean
